### ISSUE TITLE
Delayed Logout

### ISSUE THREAD

**Issue by nikkushankar** [IBM/ce-cns#1]
When the logout link is clicked the logout is not immediate. The actual logout is only getting executed from the timeout method. In your code it takes 10 seconds for the logout.

**Comment by thomassuedbroecker** [comment]
Hi @nikkushankar, your are right.

In my blog post [Simply logout from Keycloak](https://suedbroecker.net/2021/05/18/simply-logout-from-keycloak/).
The reason for this is the reuse of the interval implementation for the token update ;-)

> _"Finally, we come to the logout implementation, which is also a part of the interval implementation (so the logout takes bit) to take the advantage of the existing Keycloak javascript-adapter instance in the example."_

You find the code [here ](https://github.com/thomassuedbroecker/ce-cns/blob/master/code/web-app/src/main.js) starting at line 91.

```javascript
....
setInterval(() => {    
   console.log("--> log: interval ");    
   console.log("--> log: isAuthenticated ", store.state.user.isAuthenticated);
...
```
