### ISSUE TITLE
Request failed with status code 500 error after first login

### ISSUE THREAD

**Issue by ayatokura** [IBM/ce-cns#4]
"Request failed with status code 500" error occurs when reloading after first login.
* Region: us-south
* Browser: Chrome and firefox
![image](https://user-images.githubusercontent.com/12283147/134469787-740c20c5-0e0c-4daf-90da-ba9292ee853c.png)

**Comment by thomassuedbroecker** [comment]
@ayatokura normally it takes time to startup the containers when they are down as you see here in the video: https://youtu.be/x67_tD4APeQ?t=2609

You get the **500 Internal Server Error - HTTP**, so it seems that the **web-api** microservice, which is invoke form the **web-app** can't connect to the articles service.

Remember: 
**web-app->web-api->articles** are needed to show the articles, so please check are all application are currently running in Code-Engine?

**Comment by thomassuedbroecker** [comment]
Hi @ayatokura , 

today I verified it on my site and it worked. 

<img width="1325" alt="today" src="https://user-images.githubusercontent.com/12815392/134539191-b227139b-4516-4c33-ac9f-0646245086c3.png">

**Comment by thomassuedbroecker** [comment]
Hi @ayatokura I also verified it in the IBM Cloud Console and took 10 min to run the script and 3 min to get all application up. Summary: All worked.  Yes, it takes time, but the CPU and RAM is minimize the consumption of the free tier from Code Engine.

I noticed maybe sed command with the regular expression doesn't work anymore for the namespace, I change this and the bash scripts.

**Comment by thomassuedbroecker** [comment]
If your problem persist feel free to contact me again.
